[project]
site_name = "Mes flashcards"
site_url = "https://lfavole.github.io/flashcards/"
repo_name = "lfavole/flashcards"
repo_url = "https://github.com/lfavole/flashcards"
extra_css = ["css/overrides.css"]
extra_javascript = ["https://cdn.jsdelivr.net/npm/tablesort@5/dist/tablesort.min.js", "js/linked-tabs.js", "js/tablesort.js"]

[project.theme]
language = "fr"
features = [
    "announce.dismiss",
    "content.code.copy",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.path",
    "navigation.sections",
    "search.highlight",
    "toc.follow",
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Passer au thème clairy"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Passer au thème sombre"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Changer de thème automatiquement"

[project.theme.icon]
logo = "material/cards"
repo = "fontawesome/brands/github"
